---

- name: Install package dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ azcopy_pkg_deps }}"

- name: Check current version installed
  shell: "{{ azcopy_bin_path }}/azcopy --version 2>&1 | head -n 1 | grep {{ azcopy_version }}"
  failed_when: false
  changed_when: false
  register: version

- name: "Install azcopy {{ azcopy_version }}"
  unarchive:
    src: "{{ azcopy_pkg_url }}"
    dest: "{{ azcopy_bin_path }}"
    remote_src: yes
    exclude:
      - ThirdPartyNotice.txt
      - NOTICE.txt
    extra_opts: [--strip-components=1]
  when: version.rc != 0