---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos-7
    image: centos:7
  - name: centos-8
    image: centos:8
  - name: debian-buster
    image: debian:buster
  - name: debian-bullseye
    image: debian:bullseye
  - name: ubuntu-18-04
    image: ubuntu:18.04
  - name: ubuntu-20-04
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: ansible
