---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Check current version installed
      shell: "{{ azcopy_bin_path }}/azcopy --version 2>&1 | head -n 1 | grep {{ azcopy_version }}"
      failed_when: false
      changed_when: false
      register: version

    - name: Check installation
      fail:
        msg: "azcopy {{ azcopy_version }} installation failure"
      when: version.rc != 0

    - name: Display version installed
      debug:
        msg: "{{ version.stdout_lines }} is installed."